swagger: "2.0"
info:
  title: TradingService
  description:
    API service \@capability1=banking \@capability2=corporate \@country=de
    trading-service-v1 API service provides orchestrated services to execute Algo when given a signal
  contact:
    name: Akshay Pattan
    email: akshaypattan99@gmail.com
  version: v1
paths:
  /health:
    get:
      tags:
        - MetaInformationService
      description: "gets the current health status"
      produces:
        - application/json
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Health"
        500:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Health:
    required:
      - status
    type: object
    properties:
      status:
        type: string
        enum:
          - UP
          - DOWN
  Error:
    type: object
    properties:
      errorCode:
        type: string
      errorDescription:
        type: string
      path:
        type: string